<?php


namespace LoreSjoberg\Warp;
use LoreSjoberg\Warp\Exception\UncallableFunctionException;


/**
 * Class WordPressCurator
 *
 * Retrieves data from WordPress
 *
 * Here's why this class exists: WordPress pollutes the global namespace
 * something awful, and there's nothing we can do about that.
 *
 * However, we can voluntarily "wrap" WordPress in a class, and choose
 * to only access it through that class. Why would we want to do that?
 * The main reason is unit testing. By accessing WordPress's global functions
 * only through this class, we can easily mock it up and test without
 * instantiating all of WordPress, setting up a database, so on and so forth.
 *
 * In theory, it also allows us to substitute something else for WordPress
 * if we wanted to use the class in another context, as unlikely as that would
 * seem. Perhaps a bit more likely, someone could extend Caller
 * for their own purposes and fix certain function calls.
 *
 * At any rate, to make this work, we are using PHP's __call() magic method,
 * which in this case is the lesser of two evils. This way users have access
 * to the entirety of WordPress -- past, present, and future -- while still
 * allowing us to mock it up.
 *
 * The downside is code completion. And now, a long list of methods to help
 * with code completion.
 *
 *
 *	@method addslashes_gpc($gpc)
 *	@method add_action($tag, $function_to_add, $priority, $accepted_args)
 *	@method add_blog_option($id, $key, $value)
 *	@method add_custom_background($header_callback, $admin_header_callback, $admin_image_div_callback)
 *	@method add_custom_image_header($header_callback, $admin_header_callback, $admin_image_div_callback)
 *	@method add_existing_user_to_blog($blog_id, $user_id, $role)
 *	@method add_filter($tag, $function_to_add, $priority, $accepted_args)
 *	@method add_magic_quotes($array)
 *	@method add_menu_page($page_title, $menu_title, $capability, $menu_slug, $function, $icon_url, $position)
 *	@method add_meta_box($id, $title, $callback, $page, $context, $priority, $callback_args)
 *	@method add_new_user_to_blog($blog_id, $user_id, $role)
 *	@method add_object_page($page_title, $menu_title, $capability, $menu_slug, $function, $icon_url, $position)
 *	@method add_option($name, $value, $deprecated, $autoload)
 *	@method add_ping($post_id, $uri)
 *	@method add_post_meta($post_id, $meta_key, $meta_value, $unique)
 *	@method add_post_type_support($post_type, $supports)
 *	@method add_query_arg($param1, $param2, $old_query_or_uri)
 *	@method add_role($role, $display_name, $capabilities)
 *	@method add_shortcode($tag , $func)
 *	@method add_submenu_page($parent_slug, $page_title, $menu_title, $capability, $menu_slug, $function)
 *	@method add_theme_support($feature)
 *	@method add_user_meta($user_id, $meta_key, $meta_value, $unique)
 *	@method add_user_to_blog($blog_id, $user_id, $role)
 *	@method add_utility_page($page_title, $menu_title, $capability, $menu_slug, $function, $icon_url, $position)
 *	@method admin_notice_feed()
 *	@method admin_url($path, $scheme)
 *	@method allowed_tags()
 *	@method antispambot($emailaddy, $mailto)
 *	@method apply_filters($tag, $value, $var)
 *	@method attribute_escape($text)
 *	@method author_can($post, $capability)
 *	@method auth_redirect()
 *	@method avoid_blog_page_permalink_collision()
 *	@method backslashit($string)
 *	@method balanceTags($text, $force)
 *	@method bloginfo($show)
 *	@method bloginfo_rss($show)
 *	@method body_class($class)
 *	@method bool_from_yn($yn)
 *	@method cache_javascript_headers()
 *	@method calendar_week_mod()
 *	@method cancel_comment_reply_link()
 *	@method category_description()
 *	@method cat_is_ancestor_of($cat1, $cat2)
 *	@method check_admin_referer($action, $query_arg)
 *	@method check_ajax_referer($action, $query_arg, $die)
 *	@method check_comment($author, $email, $url, $comment, $user_ip, $user_agent, $comment_type)
 *	@method check_import_new_users()
 *	@method check_upload_mimes()
 *	@method check_upload_size($file)
 *	@method choose_primary_blog()
 *	@method clean_pre($matches)
 *	@method clean_url($url, $protocols, $context)
 *	@method comments_link()
 *	@method comments_number($zero, $one, $more)
 *	@method comments_open($post_id)
 *	@method comments_popup_link()
 *	@method comments_popup_script()
 *	@method comments_rss_link()
 *	@method comments_template($file, $separate_comments)
 *	@method comment_author($comment_ID)
 *	@method comment_author_email()
 *	@method comment_author_email_link()
 *	@method comment_author_IP()
 *	@method comment_author_link()
 *	@method comment_author_rss()
 *	@method comment_author_url()
 *	@method comment_author_url_link()
 *	@method comment_class($class)
 *	@method comment_date($d, $comment_ID)
 *	@method comment_excerpt()
 *	@method comment_form($args, $post_id)
 *	@method comment_form_title()
 *	@method comment_ID()
 *	@method comment_id_fields()
 *	@method comment_link()
 *	@method comment_reply_link()
 *	@method comment_text($comment_ID)
 *	@method comment_text_rss()
 *	@method comment_time($d)
 *	@method comment_type()
 *	@method confirm_delete_users()
 *	@method content_url($path)
 *	@method convert_chars($content, $deprecated)
 *	@method convert_smilies($text)
 *	@method count_many_users_posts($users)
 *	@method count_users($strategy)
 *	@method count_user_posts($userid)
 *	@method create_empty_blog($domain, $path, $weblog_title, $site_id)
 *	@method current_filter()
 *	@method current_theme_supports($feature)
 *	@method current_time($type, $gmt = 0)
 *	@method current_user_can($capability)
 *	@method current_user_can_for_blog($blog_id, $capability)
 *	@method dashboard_quota()
 *	@method date_i18n($dateformatstring, $unixtimestamp, $gmt)
 *	@method delete_blog_option($id, $key)
 *	@method delete_get_calendar_cache()
 *	@method delete_option($name)
 *	@method delete_post_meta($post_id, $meta_key, $meta_value)
 *	@method delete_site_transient($transient)
 *	@method delete_transient($transient)
 *	@method delete_user_meta($user_id, $meta_key, $meta_value)
 *	@method did_action($tag)
 *	@method discover_pingback_server_uri($url, $deprecated)
 *	@method display_space_usage()
 *	@method domain_exists($domain, $path, $site_id)
 *	@method do_action($tag, $arg)
 *	@method do_action_ref_array($tag, $arg)
 *	@method do_all_pings()
 *	@method do_enclose($content, $post_ID)
 *	@method do_feed()
 *	@method do_feed_atom($for_comments)
 *	@method do_feed_rdf()
 *	@method do_feed_rss()
 *	@method do_feed_rss2($for_comments)
 *	@method do_robots()
 *	@method do_shortcode($content)
 *	@method do_shortcode_tag($m)
 *	@method do_trackbacks($post_id)
 *	@method dynamic_sidebar($index)
 *	@method edit_bookmark_link($link, $before, $after, $bookmark)
 *	@method edit_comment_link($link, $before, $after)
 *	@method edit_post_link($link, $before, $after, $id)
 *	@method edit_tag_link($link, $before, $after, $tag)
 *	@method email_exists($email)
 *	@method ent2ncr($text)
 *	@method esc_attr($text)
 *	@method esc_html($text)
 *	@method esc_js($text)
 *	@method esc_textarea($text)
 *	@method esc_url($url, array $protocols = null)
 *	@method extract_from_markers($filename, $marker)
 *	@method fetch_feed($uri)
 *	@method filter_SSL($url)
 *	@method fix_import_form_size($size)
 *	@method fix_phpmailer_messageid($phpmailer)
 *	@method force_balance_tags($text)
 *	@method force_ssl_content($force)
 *	@method format_code_lang($code)
 *	@method format_to_edit($content, $richedit)
 *	@method format_to_post($content)
 *	@method form_option($option)
 *	@method add_cap($role, $cap, $grant)
 *	@method remove_cap($role, $cap)
 *	@method funky_javascript_fix($text)
 *	@method generic_ping($post_id)
 *	@method get_404_template()
 *	@method get_active_blog_for_user($user_id)
 *	@method get_adjacent_post($in_same_cat, $excluded_categories, $previous)
 *	@method get_admin_url($blog_id, $path, $scheme)
 *	@method get_admin_users_for_domain($sitedomain, $path)
 *	@method get_alloptions()
 *	@method get_all_category_ids()
 *	@method get_all_page_ids()
 *	@method get_ancestors($object_id, $object_type)
 *	@method get_approved_comments($post_id)
 *	@method get_archives_link()
 *	@method get_archive_template()
 *	@method get_attached_file($attachment_id, $unfiltered)
 *	@method get_attachment_link($id, $size, $permalink, $icon, $text)
 *	@method get_attachment_template()
 *	@method get_author_feed_link($author_id, $feed)
 *	@method get_author_posts_url($author_id, $author_nicename)
 *	@method get_author_template()
 *	@method get_avatar($id_or_email, $size, $default, $alt)
 *	@method get_blogaddress_by_domain($domain, $path)
 *	@method get_blogaddress_by_id($blog_id)
 *	@method get_blogaddress_by_name($blogname)
 *	@method get_bloginfo($show, $filter)
 *	@method get_bloginfo_rss($show)
 *	@method get_blogs_of_user($user_id)
 *	@method get_blog_count($id)
 *	@method get_blog_details($blog_id)
 *	@method get_blog_id_from_url($domain, $path)
 *	@method get_blog_option($blog_id, $setting , $default)
 *	@method get_blog_permalink($_blog_id, $post_id)
 *	@method get_blog_post($blog_id, $post_id)
 *	@method get_blog_status($id, $pref)
 *	@method get_bookmark($bookmark, $output, $filter)
 *	@method get_bookmarks($args)
 *	@method get_bookmark_field()
 *	@method get_boundary_post($in_same_cat, $excluded_categories, $start)
 *	@method get_calendar($initial, $echo)
 *	@method get_categories($args)
 *	@method get_category($category, $output, $filter)
 *	@method get_category_by_path($category_path, $full_match, $output)
 *	@method get_category_by_slug($slug)
 *	@method get_category_feed_link($cat_id, $feed)
 *	@method get_category_link($category_id)
 *	@method get_category_parents($category, $display_link, $separator, $nice_name)
 *	@method get_category_template|get_category_template()
 *	@method get_cat_ID($cat_name)
 *	@method get_cat_name($cat_id)
 *	@method get_children($args, $output)
 *	@method get_comment($id, $output)
 *	@method get_comments($args)
 *	@method get_comments_popup_template()
 *	@method get_comment_author_rss()
 *	@method get_comment_link($comment, $args)
 *	@method get_comment_text($comment_ID)
 *	@method get_currentuserinfo()
 *	@method get_current_blog_id()
 *	@method get_current_site()
 *	@method get_current_site_name($current_site)
 *	@method get_current_theme()
 *	@method get_dashboard_blog()
 *	@method get_date_from_gmt($string, $format)
 *	@method get_date_template()
 *	@method get_day_link($year, $month, $day)
 *	@method get_dirsize($directory)
 *	@method get_edit_post_link($id, $context)
 *	@method get_enclosed($post_id)
 *	@method get_extended($post)
 *	@method get_footer($name)
 *	@method get_gmt_from_date()
 *	@method get_header($string)
 *	@method get_header_image()
 *	@method get_header_textcolor()
 *	@method get_home_template()
 *	@method get_home_url($blog_id, $path, $scheme)
 *	@method get_id_from_blogname($name)
 *	@method get_lastcommentmodified($timezone)
 *	@method get_lastpostdate($timezone)
 *	@method get_lastpostmodified($timezone)
 *	@method get_last_updated($depreciated, $start, $quantity)
 *	@method get_locale_stylesheet_uri()
 *	@method get_month_link($year, $month)
 *	@method get_most_recent_post_of_user($user_id)
 *	@method get_next_post($in_same_cat, $excluded_categories)
 *	@method get_num_queries()
 *	@method get_option($show, $default)
 *	@method get_page($page_id)
 *	@method get_paged_template()
 *	@method get_pages($args)
 *	@method get_page_by_path($page_path, $output, $post_type)
 *	@method get_page_by_title($page_title, $output, $post_type)
 *	@method get_page_children($page_id, $pages)
 *	@method get_page_hierarchy($posts, $parent)
 *	@method get_page_link($id, $leavename, $sample)
 *	@method get_page_template()
 *	@method get_page_uri($page_id)
 *	@method get_permalink($id)
 *	@method get_post($post_id, $output = 'OBJECT', $filter = 'raw')
 *	@method get_posts($args)
 *	@method get_post_ancestors($post)
 *	@method get_post_comments_feed_link($post_id, $feed)
 *	@method get_post_custom($post_id)
 *	@method get_post_custom_keys($post_id)
 *	@method get_post_custom_values($key, $post_id)
 *  @method get_post_field( $field, $post_id, $context = null)
 *	@method get_post_meta($post_id, $key, $single)
 *	@method get_post_mime_type($ID)
 *	@method get_post_permalink()
 *	@method get_post_status($ID)
 *	@method get_post_thumbnail_id($post_id = null)
 *	@method get_post_type($post)
 *	@method get_post_type_capabilities($args)
 *	@method get_post_type_labels($post_type_object)
 *	@method get_post_type_object($post_type)
 *	@method get_post_types($args, $output, $operator)
 *	@method get_previous_post($in_same_cat, $excluded_categories)
 *	@method get_profile($field, $user)
 *	@method get_pung($post_id)
 * 	@method get_queried_object()
 *	@method get_query_template($type)
 *	@method get_query_var($var)
 *	@method get_role($role)
 *	@method get_search_comments_feed_link($search_query, $feed)
 *	@method get_search_feed_link($search_query, $feed)
 *	@method get_search_form($echo)
 *	@method get_search_link()
 *	@method get_search_query()
 *	@method get_search_template()
 *	@method get_shortcode_regex()
 *	@method get_sidebar($name)
 *	@method get_single_template()
 *	@method get_sitestats()
 *	@method get_site_allowed_themes()
 *	@method get_site_option($option, $default , $use_cache)
 *	@method get_site_transient($transient)
 *	@method get_site_url($blog_id, $path, $scheme)
 *	@method get_space_allowed()
 *	@method get_stylesheet()
 *	@method get_stylesheet_directory()
 *	@method get_stylesheet_directory_uri()
 *	@method get_stylesheet_uri()
 *	@method get_super_admins()
 *	@method get_tag($tag, $output, $filter)
 *	@method get_tags($orderby, $order, $hide_empty, $exclude, $include, $number, $offset, $fields, $slug, $hierarchical, $search, $name__like)
 *	@method get_tag_link($tag_id)
 *	@method get_tag_template()
 *	@method get_taxonomies($args, $output, $operator)
 *	@method get_taxonomy_template()
 *	@method get_template()
 *	@method get_template_directory()
 *	@method get_template_directory_uri()
 *	@method get_template_part($slug, $name)
 *	@method get_term($term, $taxonomy, $output, $filter)
 *	@method get_terms(array $args, array $deprecated = [])
 *	@method get_term_by($field, $value, $taxonomy, $output, $filter)
 *	@method get_term_children($term, $taxonomy)
 *	@method get_term_link($term, $taxonomy)
 *	@method get_theme($theme)
 *	@method get_themes()
 *	@method get_theme_data($theme_filename)
 *	@method get_theme_mod($name, $default)
 *	@method get_theme_root()
 *	@method get_theme_roots()
 *	@method get_theme_root_uri()
 *	@method get_the_author()
 *	@method get_the_author_link()
 *	@method get_the_category($id)
 *	@method get_the_category_by_ID($cat_ID)
 *	@method get_the_category_rss($type)
 *	@method get_the_content($more_link_text, $stripteaser, $more_file)
 *	@method get_the_date()
 *	@method get_the_excerpt($deprecated)
 *	@method get_the_ID()
 *	@method get_the_post_thumbnail($post_id, $size, $attr)
 *	@method get_the_tags($id)
 *	@method get_the_tag_list($before, $sep, $after)
 *	@method get_the_terms($id, $taxonomy)
 *	@method get_the_term_list($id, $taxonomy, $before, $sep, $after)
 *	@method get_the_time($d, $post)
 *	@method get_the_title($ID)
 *	@method get_the_title_rss()
 *	@method get_transient($transient)
 *	@method get_to_ping($post_id)
 *	@method get_upload_space_available()
 *	@method get_userdata($userid)
 *	@method get_userdatabylogin($user_login)
 *	@method get_usernumposts($userid)
 *	@method get_users($args)
 *	@method get_users_of_blog()
 *	@method get_user_count()
 *	@method get_user_id_from_string($string)
 *	@method get_user_meta($user_id, $key, $single)
 *	@method get_user_option($option, $user)
 *	@method get_weekstartend($mysqlstring, $start_of_week)
 *	@method get_year_link($year)
 *	@method global_terms($term_id, $deprecated)
 *	@method grant_super_admin($user_id)
 *	@method has_action($tag, $function_to_check)
 *	@method has_filter($tag, $function_to_check)
 *	@method has_nav_menu($location)
 *	@method has_post_thumbnail()
 *	@method has_tag($tag)
 *	@method has_term($term, $taxonomy, $post)
 *	@method have_comments()
 *	@method header_image()
 *	@method header_textcolor()
 *	@method home_url($path, $scheme)
 *	@method htmlentities2($myHTML)
 *	@method human_time_diff($from, $to)
 *	@method includes_url($path)
 *	@method insert_blog($domain, $path, $site_id)
 *	@method insert_with_markers($filename, $marker, $insertion)
 *	@method install_blog($blog_id, $blog_title)
 *	@method install_blog_defaults($blog_id, $user_id)
 *	@method in_category($category, $_post)
 *	@method iso8601_timezone_to_offset($timezone)
 *	@method iso8601_to_datetime($date_string, $timezone)
 *	@method is_404()
 *	@method is_admin()
 *	@method is_archive()
 *	@method is_archived()
 *	@method is_attachment()
 *	@method is_author($author)
 *	@method is_blog_installed()
 *	@method is_blog_user($blog_id)
 *	@method is_category($category)
 *	@method is_comments_popup()
 *	@method is_date()
 *	@method is_day()
 *	@method is_email($email)
 *	@method is_email_address_unsafe($user_email)
 *	@method is_feed()
 *	@method is_front_page()
 *	@method is_home()
 *	@method is_local_attachment($url)
 *	@method is_main_site($blog_id)
 *	@method is_month()
 *	@method is_new_day()
 *	@method is_page($page)
 *	@method is_paged()
 *	@method is_page_template($template)
 *	@method is_post_type_archive($post_types)
 *	@method is_post_type_hierarchical($post_type)
 *	@method is_preview()
 *	@method is_search()
 *	@method is_serialized($data)
 *	@method is_serialized_string($data)
 *	@method is_single($post)
 *	@method is_singular($post_types)
 *	@method is_ssl()
 *	@method is_sticky($post_ID)
 *	@method is_subdomain_install()
 *	@method is_super_admin($user_id)
 *	@method is_tag($slug)
 *	@method is_tax($taxonomy, $term)
 *	@method is_taxonomy_hierarchical($taxonomy)
 *	@method is_time()
 *	@method is_trackback()
 *	@method is_upload_space_available()
 *	@method is_user_logged_in()
 *	@method is_user_member_of_blog()
 *	@method is_user_option_local($key, $user_id, $blog_id)
 *	@method is_user_spammy($username)
 *	@method is_year()
 *	@method load_template($_template_file)
 *	@method locale_stylesheet()
 *	@method locate_template($template_names, $load, $require_once)
 *	@method log_app($label, $msg)
 *	@method make_clickable($ret)
 *	@method map_meta_cap($cap, $user_id)
 *	@method maybe_add_existing_user_to_blog()
 *	@method maybe_redirect_404()
 *	@method maybe_serialize($data)
 *	@method maybe_unserialize($original)
 *	@method menu_page_url($menu_slug, $echo)
 *	@method merge_filters($tag)
 *	@method ms_cookie_constants()
 *	@method ms_deprecated_blogs_file()
 *	@method ms_file_constants()
 *	@method ms_not_installed()
 *	@method ms_site_check()
 *	@method ms_subdomain_constants()
 *	@method ms_upload_constants()
 *	@method mu_dropdown_languages($lang_files, $current)
 *	@method mysql2date($dateformatstring, $mysqlstring, $translate = true)
 *	@method newblog_notify_siteadmin($blog_id, $deprecated)
 *	@method newuser_notify_siteadmin($user_id)
 *	@method new_user_email_admin_notice()
 *	@method network_admin_url($path, $scheme)
 *	@method network_home_url($path, $scheme)
 *	@method network_site_url($path, $scheme)
 *	@method next_comments_link($label, $max_page)
 *	@method next_image_link()
 *	@method next_posts_link()
 *	@method next_post_link()
 *	@method nocache_headers()
 *	@method page_uri_index()
 *	@method paginate_comments_links($args)
 *	@method permalink_anchor()
 *	@method permalink_comments_rss()
 *	@method permalink_single_rss($file)
 *	@method pingback($content, $post_ID)
 *	@method pings_open($post_id)
 *	@method plugins_url($path, $plugin)
 *	@method plugin_basename($file)
 *	@method plugin_dir_url($file)
 *	@method plugin_dir_path($file)
 *	@method popuplinks($text)
 *	@method posts_nav_link()
 *	@method post_class()
 *	@method post_comments_feed_link($link_text, $post_id, $feed)
 *	@method post_password_required()
 *	@method post_permalink()
 *	@method post_type_archive_title($prefix, $display)
 *	@method post_type_supports($post_type, $supports)
 *	@method preview_theme()
 *	@method preview_theme_ob_filter($content)
 *	@method preview_theme_ob_filter_callback($matches)
 *	@method previous_comments_link($label)
 *	@method previous_image_link()
 *	@method previous_posts_link()
 *	@method previous_post_link()
 *	@method privacy_ping_filter($sites)
 *	@method recurse_dirsize($directory)
 *	@method redirect_mu_dashboard()
 *	@method redirect_this_site($deprecated)
 *	@method redirect_user_to_blog()
 *	@method refresh_blog_details($blog_id)
 *	@method refresh_user_details($id)
 *	@method register_activation_hook($file, $function)
 *	@method register_deactivation_hook($file, $function)
 *	@method register_nav_menu($location, $description)
 *	@method register_nav_menus($locations)
 *	@method register_post_type($post_type, $args)
 *	@method register_setting($option_group, $option_name, $sanitize_callback)
 *	@method register_taxonomy($taxonomy, $object_type, $args)
 *	@method register_taxonomy_for_object_type($taxonomy, $object_type)
 *	@method register_theme_directory($directory)
 *	@method remove_accents($string)
 *	@method remove_action($tag, $function_to_remove, $priority, $accepted_args)
 *	@method remove_all_actions($tag, $priority)
 *	@method remove_all_filters($tag, $priority)
 *	@method remove_all_shortcodes()
 *	@method remove_filter($tag, $function_to_remove, $priority, $accepted_args)
 *	@method remove_meta_box($id, $page, $context)
 *	@method remove_post_type_support($post_type, $supports)
 *	@method remove_query_arg($key, $query)
 *	@method remove_role($role)
 *	@method remove_shortcode($tag)
 *	@method remove_theme_mod($name)
 *	@method remove_theme_mods()
 *	@method remove_user_from_blog($user_id, $blog_id, $reassign)
 *	@method rewind_posts()
 *	@method require_if_theme_supports($feature, $include)
 *	@method restore_current_blog()
 *	@method revoke_super_admin($user_id)
 *	@method rss_enclosure()
 *	@method sanitize_comment_cookies()
 *	@method sanitize_email($email)
 *	@method sanitize_file_name($name)
 *	@method sanitize_title($title, $fallback_title)
 *	@method sanitize_title_with_dashes($title)
 *	@method sanitize_user($username, $strict)
 *	@method search_theme_directories()
 *	@method secret_salt_warning()
 *	@method seems_utf8($str)
 *	@method send_confirmation_on_profile_email()
 *	@method settings_fields($option_group)
 *	@method set_current_user($id, $name)
 *	@method set_post_type($post_id, $post_type)
 *	@method set_theme_mod($name, $value)
 *	@method set_site_transient($transient, $value, $expiration)
 *	@method set_transient($transient, $value, $expiration)
 *	@method shortcode_atts($pairs , $atts)
 *	@method shortcode_parse_atts($text)
 *	@method show_post_thumbnail_warning()
 *	@method signup_nonce_check($result)
 *	@method signup_nonce_fields()
 *	@method single_cat_title()
 *	@method single_month_title()
 *	@method single_post_title()
 *	@method single_tag_title()
 *	@method single_term_title()
 *	@method site_admin_notice()
 *	@method site_url($path, $scheme)
 *	@method spawn_cron($local_time)
 *	@method status_header($header)
 *	@method sticky_class()
 *	@method stripslashes_deep($value)
 *	@method strip_shortcodes($content)
 *	@method switch_theme($template, $stylesheet)
 *	@method switch_to_blog($new_blog, $validate)
 *	@method sync_category_tag_slugs($term, $taxonomy)
 *	@method tag_description()
 *	@method taxonomy_exists($taxonomy)
 *	@method term_description()
 *	@method term_exists($term, $taxonomy, $parent)
 *	@method the_attachment_link()
 *	@method the_author()
 *	@method the_author_link()
 *	@method the_author_meta()
 *	@method the_author_posts()
 *	@method the_author_posts_link()
 *	@method the_category()
 *	@method the_category_rss($type)
 *	@method the_content()
 *	@method the_content_rss($more_link_text, $stripteaser, $more_file, $cut, $encode_html)
 *	@method the_date($format, $before, $after, $echo)
 *	@method the_date_xml()
 *	@method the_excerpt()
 *	@method the_excerpt_rss()
 *	@method the_feed_link()
 *	@method the_ID()
 *	@method the_meta()
 *	@method the_modified_author()
 *	@method the_modified_date()
 *	@method the_modified_time()
 *	@method the_permalink()
 *	@method the_post_thumbnail()
 *	@method the_search_query()
 *	@method the_shortlink()
 *	@method the_tags()
 *	@method the_taxonomies()
 *	@method the_terms()
 *	@method the_time()
 *	@method the_title()
 *	@method the_title_attribute()
 *	@method the_title_rss()
 *	@method trackback($trackback_url, $title, $excerpt, $ID)
 *	@method trackback_url()
 *	@method trackback_url_list($tb_list, $post_id)
 *	@method trailingslashit($string)
 *	@method unregister_nav_menu($location)
 *	@method unregister_setting($option_group, $option_name, $sanitize_callback)
 *	@method untrailingslashit($string)
 *	@method update_archived($id, $archived)
 *	@method update_attached_file($attachment_id, $file)
 *	@method update_blog_details($blog_id, $details)
 *	@method update_blog_option($id, $key, $value, $depreciated)
 *	@method update_blog_public($old_value, $value)
 *	@method update_blog_status($blog_id, $pref, $value, $refresh)
 *	@method update_option($option_name, $newvalue)
 *	@method update_option_new_admin_email($old_value, $value)
 *	@method update_posts_count($deprecated)
 *	@method update_post_meta($post_id, $meta_key, $meta_value, $prev_value)
 *	@method update_user_meta($user_id, $meta_key, $meta_value, $prev_value)
 *	@method update_user_option($user_id, $option_name, $newvalue, $global)
 *	@method update_user_status($id, $pref, $value, $deprecated)
 *	@method upload_is_file_too_big($upload)
 *	@method upload_is_user_over_quota($echo)
 *	@method upload_size_limit_filter($size)
 *	@method upload_space_setting($id)
 *	@method url_shorten($url)
 *	@method username_exists($username)
 *	@method users_can_register_signup_filter()
 *	@method user_can($user, $capability)
 *	@method user_pass_ok($user_login, $user_pass)
 *	@method user_trailingslashit()
 *	@method utf8_uri_encode($utf8_string, $length)
 *	@method validate_current_theme()
 *	@method validate_username($username)
 *	@method walk_nav_menu_tree()
 *	@method weblog_ping($server, $path)
 *	@method welcome_user_msg_filter($text)
 *	@method wordpressmu_wp_mail_from()
 *	@method wp($query_vars)
 *	@method wpautop($foo, $br)
 *	@method wpmu_activate_signup($key)
 *	@method wpmu_admin_redirect_add_updated_param()
 *	@method wpmu_create_blog($domain, $path, $title, $user_id, $meta, $site_id)
 *	@method wpmu_create_user($user_name, $password, $email)
 *	@method wpmu_current_site()
 *	@method wpmu_delete_blog($blog_id, $drop)
 *	@method wpmu_delete_user($id)
 *	@method wpmu_get_blog_allowedthemes($blog_id)
 *	@method wpmu_log_new_registrations($blog_id, $user_id)
 *	@method wpmu_signup_blog($domain, $path, $title, $user, $user_email, $meta)
 *	@method wpmu_signup_blog_notification($domain, $path, $title, $user, $user_email, $key, $meta)
 *	@method wpmu_signup_user($user, $user_email, $meta)
 *	@method wpmu_signup_user_notification($user, $user_email, $key, $meta)
 *	@method wpmu_update_blogs_date()
 *	@method wpmu_validate_blog_signup($blogname, $blog_title, $user)
 *	@method wpmu_validate_user_signup($user_name, $user_email)
 *	@method wpmu_welcome_notification($blog_id, $user_id, $password, $title, $meta)
 *	@method wpmu_welcome_user_notification($user_id, $password, $meta)
 *	@method wptexturize($text)
 *	@method wp_ajaxurl()
 *	@method wp_allow_comment($commentdata)
 *	@method wp_attachment_is_image($post_id)
 *	@method wp_category_checklist()
 *	@method wp_check_filetype($filename, $mimes)
 *	@method wp_check_for_changed_slugs($post_id)
 *	@method wp_clearcookie()
 *	@method wp_clear_scheduled_hook($hook, $args)
 *	@method wp_count_comments($post_id)
 *	@method wp_count_posts($type, $perm)
 *	@method wp_create_category($cat_name, $parent)
 *	@method wp_create_nonce($action)
 *	@method wp_create_user($username, $password, $email)
 *	@method wp_cron()
 *	@method wp_delete_attachment()
 *	@method wp_delete_category($cat_ID)
 *	@method wp_delete_comment($attachmentid, $force_delete = false)
 *	@method wp_delete_post($postid, $force_delete)
 *	@method wp_delete_term($term_id, $taxonomy, $args)
 *	@method wp_delete_user($id, $reassign)
 *	@method wp_dequeue_script($handle)
 *	@method wp_deregister_script($handle)
 *	@method wp_die($message, $title, $args)
 *	@method wp_dropdown_categories()
 *	@method wp_dropdown_users()
 *	@method wp_enqueue_script($handle,$src,$deps,$ver,$in_footer)
 *	@method wp_enqueue_style($handle, $src, $deps, $ver, $media)
 *	@method wp_explain_nonce($action)
 *	@method wp_filter_comment($commentdata)
 *	@method wp_filter_kses($data)
 *	@method wp_filter_nohtml_kses($data)
 *	@method wp_filter_post_kses($data)
 *	@method wp_footer()
 *	@method wp_generate_tag_cloud()
 *	@method wp_generate_attachment_metadeta($attachment_id, $file)
 *	@method wp_get_archives($args)
 *	@method wp_get_attachment_image($attachment_id, $size, $icon, $attr)
 *	@method wp_get_attachment_image_src($attachment_id, $size, $icon)
 *	@method wp_get_attachment_link($id, $size, $permalink, $icon, $text)
 *	@method wp_get_attachment_metadata($post_id, $unfiltered)
 *	@method wp_get_attachment_thumb_file($post_id)
 *	@method wp_get_attachment_thumb_url($post_id)
 *	@method wp_get_attachment_url($id)
 *	@method wp_get_comment_status($comment_id)
 *	@method wp_get_cookie_login()
 *	@method wp_get_current_commenter()
 *	@method wp_get_current_user()
 *	@method wp_get_http_headers($url, $deprecated)
 *	@method wp_get_nav_menu_items($menu, $args)
 *	@method wp_get_object_terms($object_ids, $taxonomies, $args)
 *	@method wp_get_original_referer()
 *	@method wp_get_post_categories($post_id, $args)
 *	@method wp_get_post_tags($post_id, $args)
 *	@method wp_get_post_terms($post_id, $taxonomy, $args)
 *	@method wp_get_recent_posts($args)
 *	@method wp_get_referer()
 *	@method wp_get_schedule($hook, $args)
 *	@method wp_get_schedules()
 *	@method wp_get_shortlink()
 *	@method wp_get_single_post($postid, $mode)
 *	@method wp_hash($data, $scheme)
 *	@method wp_head()
 *	@method wp_insert_attachment($attachment, $filename, $parent_post_id)
 *	@method wp_insert_category($catarr, $wp_error)
 *	@method wp_insert_comment($commentdata)
 *	@method wp_insert_post($post, $wp_error)
 *	@method wp_insert_term($term, $taxonomy, $args)
 *	@method wp_insert_user($userdata)
 *	@method wp_iso_descrambler($string)
 *	@method wp_kses($string, $allowed_html, $allowed_protocols)
 *	@method wp_kses_array_lc($inarray)
 *	@method wp_kses_attr($element, $attr, $allowed_html, $allowed_protocols)
 *	@method wp_kses_bad_protocol($string, $allowed_protocols)
 *	@method wp_kses_bad_protocol_once($string, $allowed_protocols)
 *	@method wp_kses_bad_protocol_once2($matches)
 *	@method wp_kses_check_attr_val($value, $vless, $checkname, $checkvalue)
 *	@method wp_kses_decode_entities($string)
 *	@method wp_kses_hair($attr, $allowed_protocols)
 *	@method wp_kses_hook($string, $allowed_html, $allowed_protocols)
 *	@method wp_kses_html_error($string)
 *	@method wp_kses_js_entities($string)
 *	@method wp_kses_normalize_entities($string)
 *	@method wp_kses_normalize_entities2($matches)
 *	@method wp_kses_no_null($string)
 *	@method wp_kses_split($string, $allowed_html, $allowed_protocols)
 *	@method wp_kses_split2($string, $allowed_html, $allowed_protocols)
 *	@method wp_kses_stripslashes($string)
 *	@method wp_kses_version()
 *	@method wp_link_pages()
 *	@method wp_list_authors()
 *	@method wp_list_bookmarks($args)
 *	@method wp_list_categories($args)
 *	@method wp_list_comments($args)
 *	@method wp_list_pages($args)
 *	@method wp_loginout()
 *	@method wp_login_form()
 *	@method wp_login_url()
 *	@method wp_logout()
 *	@method wp_logout_url()
 *	@method wp_lostpassword_url()
 *	@method wp_mail($to, $subject, $message, $headers, $attachments)
 *	@method wp_make_link_relative($link)
 *	@method wp_meta()
 *	@method wp_mime_type_icon($mime)
 *	@method wp_mkdir_p($target)
 *	@method wp_nav_menu($args)
 *	@method wp_new_comment($commentdata)
 *	@method wp_new_user_notification($user_id, $plaintext_pass)
 *	@method wp_next_scheduled($hook, $args)
 *	@method wp_nonce_ays($action)
 *	@method wp_nonce_field($action, $name, $referer, $echo)
 *	@method wp_nonce_url($actionurl, $action)
 *	@method wp_notify_moderator($comment_id)
 *	@method wp_notify_postauthor($comment_id, $comment_type)
 *	@method wp_original_referer_field($echo, $jump_back_to)
 *	@method wp_page_menu($args)
 *	@method wp_parse_args($args)
 *	@method wp_publish_post($post_id)
 *	@method wp_redirect($location, $status)
 *	@method wp_referer_field($echo)
 *	@method wp_register()
 *	@method wp_register_script($handle, $src, $deps, $ver, $in_footer)
 *	@method wp_rel_nofollow($text)
 *	@method wp_remote_fopen($uri)
 *	@method wp_reschedule_event($timestamp, $recurrence, $hook, $args)
 *	@method wp_reset_postdata()
 *	@method wp_reset_query()
 *	@method wp_richedit_pre($text)
 *	@method wp_salt($scheme)
 *	@method wp_schedule_event($timestamp, $recurrence, $hook, $args)
 *	@method wp_schedule_single_event($timestamp, $hook, $args)
 *	@method wp_set_auth_cookie($user_id, $remember, $secure)
 *	@method wp_set_comment_status($comment_id, $comment_status)
 *	@method wp_set_current_user($id, $name)
 *	@method wp_set_object_terms($object_id, $terms, $taxonomy, $append)
 *	@method wp_set_post_categories($post_ID, $post_categories)
 *	@method wp_set_post_tags($post_ID, $tags, $append)
 *	@method wp_set_post_terms($post_ID, $tags, $taxonomy, $append)
 *	@method wp_shortlink_header()
 *	@method wp_shortlink_wp_head()
 *	@method wp_signon($credentials, $secure_cookie)
 *	@method wp_specialchars($text, $quotes)
 *	@method wp_tag_cloud()
 *	@method wp_terms_checklist()
 *	@method wp_throttle_comment_flood($block, $time_lastcomment, $time_newcomment)
 *	@method wp_title()
 *	@method wp_trim_excerpt($text)
 *	@method wp_unschedule_event($timestamp, $schedule_hook, $original_args)
 *	@method wp_update_attachment_metadata($post_id, $data)
 *	@method wp_update_comment($commentarr)
 *	@method wp_update_comment_count($post_id, $do_deferred)
 *	@method wp_update_post($post)
 *	@method wp_update_term($term_id, $taxonomy, $args)
 *	@method wp_update_user($userdata)
 *	@method wp_upload_bits($name, $deprecated, $bits, $time)
 *	@method wp_upload_dir(string $time = null, bool $create_dir = true, bool $refresh_cache = false)
 *	@method wp_verify_nonce($nonce, $action)
 *	@method xmlrpc_getpostcategory($content)
 *	@method xmlrpc_getposttitle($content)
 *	@method xmlrpc_removepostdata($content)
 *	@method zeroise($number, $threshold)
 *	@method _admin_notice_multisite_activate_plugins_page()
 *
 * @package LoreSjoberg
 *
 */
class Warp
{

    /**
     * @param $function
     * @param $arguments
     *
     * @return mixed
     */
    public function __call($function, $arguments) {

        if (function_exists($function)) {
            return call_user_func_array($function, $arguments);
        }

        throw new UncallableFunctionException('Function ' . $function . ' does not exist.');
    }

}